name: Run Scenarios + Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-all:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run all scenarios with verify + JSON
        run: make run-all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collapse-artifacts
          path: artifacts/

